create or replace FUNCTION PROC_LOGIN_USUARIO(P_USUARIO IN VARCHAR2, P_SENHA IN VARCHAR2) 
RETURN BOOLEAN
AS
MVAL NUMBER := 0;
BEGIN
SELECT 1 INTO MVAL FROM USUARIOS U
WHERE UPPER(U.ID) = UPPER(P_USUARIO)
AND U.SENHA = P_SENHA
AND U.STATUS = 'Y';
RETURN (TRUE);
EXCEPTION
WHEN NO_DATA_FOUND THEN
RETURN FALSE;
END;
/