CREATE TABLE "COMPONENTES" 
   (	"ID_COMP" NUMBER, 
	"DS_COMP" VARCHAR2(100), 
	 CONSTRAINT "PK_ID_COMP" PRIMARY KEY ("ID_COMP")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DISPENSARIOS" 
   (	"ID_DISP" NUMBER, 
	"DS_DISP" VARCHAR2(100), 
	 CONSTRAINT "PK_ID_DISP" PRIMARY KEY ("ID_DISP")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ESTOQUE" 
   (	"CODIGO" NUMBER NOT NULL ENABLE, 
	"COD_PROD" NUMBER NOT NULL ENABLE, 
	"NM_PROD" VARCHAR2(200) NOT NULL ENABLE, 
	"VALID_PROD" DATE NOT NULL ENABLE, 
	"DTA_ENTREGA" DATE NOT NULL ENABLE, 
	"ID_POSTO" NUMBER NOT NULL ENABLE, 
	"QUANT" NUMBER NOT NULL ENABLE, 
	"ID_FUNC" NUMBER, 
	 CONSTRAINT "PK_COD_LOTE" PRIMARY KEY ("CODIGO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ESTOQUE_AUXILIAR" 
   (	"CODIGO" NUMBER, 
	"PRODUTO" VARCHAR2(200 CHAR), 
	"QUANTIDADE" NUMBER, 
	"VALIDADE" DATE, 
	"ENTREGA" DATE, 
	"POSTO" VARCHAR2(120 CHAR)
   ) ;

  CREATE TABLE "FUNCIONARIOS" 
   (	"ID_FUNC" NUMBER, 
	"NM_FUNC" VARCHAR2(50), 
	"DTA_NASC" DATE, 
	"ID_FUNCAO" NUMBER, 
	"SBRNM_FUNC" VARCHAR2(50), 
	 CONSTRAINT "PK_ID_FUNC" PRIMARY KEY ("ID_FUNC")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "MEDICAMENTOS_AUXILIAR" 
   (	"COD_PROD" NUMBER, 
	"CPF_CLIENTE" VARCHAR2(14), 
	"NM_PROD" VARCHAR2(200), 
	"QTD_PROD" NUMBER, 
	"ID" NUMBER NOT NULL ENABLE, 
	"ID_RCT" NUMBER, 
	"LOTE" NUMBER, 
	"ID_POSTO" NUMBER, 
	"COD_PED" NUMBER, 
	 CONSTRAINT "PK_ID" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PACIENTES" 
   (	"CPF" VARCHAR2(14), 
	"NOME" VARCHAR2(50), 
	"SOBRENOME" VARCHAR2(50), 
	 CONSTRAINT "PK_CPF" PRIMARY KEY ("CPF")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PEDIDOS" 
   (	"COD_PED" NUMBER, 
	"DS_PED" VARCHAR2(255), 
	"DTA_PED" DATE NOT NULL ENABLE, 
	"ID_STATUS" NUMBER NOT NULL ENABLE, 
	"DTA_ATT_PED" DATE NOT NULL ENABLE, 
	"ID_FUNC" NUMBER, 
	"ID_TIP_PED" NUMBER, 
	"ID_POSTO" NUMBER, 
	 PRIMARY KEY ("COD_PED")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PEDIDOS_PRODUTOS" 
   (	"COD_PROD" NUMBER NOT NULL ENABLE, 
	"COD_PED" NUMBER NOT NULL ENABLE, 
	"QTD_PROD" NUMBER NOT NULL ENABLE
   ) ;

  CREATE TABLE "POSTOS" 
   (	"ID_POSTO" NUMBER, 
	"DS_POSTO" VARCHAR2(120), 
	"ENDERECO" VARCHAR2(120), 
	"TELEFONE" VARCHAR2(120), 
	"EMAIL" VARCHAR2(120), 
	"ID_TIP_POSTO" NUMBER, 
	 PRIMARY KEY ("ID_POSTO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "POSTOS_PRODUTOS" 
   (	"ID_POSTO" NUMBER, 
	"COD_PROD" NUMBER
   ) ;

  CREATE TABLE "PRODUTOS" 
   (	"COD_PROD" NUMBER, 
	"DS_PROD" VARCHAR2(200) NOT NULL ENABLE, 
	"ID_COMP" NUMBER NOT NULL ENABLE, 
	"ID_DISP" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("COD_PROD")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PROFISSOES" 
   (	"ID_FUNCAO" NUMBER, 
	"DS_FUNCAO" VARCHAR2(50), 
	 CONSTRAINT "PK_ID_FUNCAO" PRIMARY KEY ("ID_FUNCAO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "RECEITAS" 
   (	"DS_RCT" VARCHAR2(200), 
	"NM_MEDICO" VARCHAR2(120), 
	"CPF_CLIENTE" VARCHAR2(14), 
	"ID_POSTO" NUMBER NOT NULL ENABLE, 
	"ID_RCT" NUMBER NOT NULL ENABLE, 
	"DTA_PED" DATE, 
	"ID_FUNC" NUMBER, 
	"NM_PESSOA" VARCHAR2(200), 
	 CONSTRAINT "PK_ID_RCT" PRIMARY KEY ("ID_RCT")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "RECEITAS_PRODUTOS" 
   (	"COD_PROD" NUMBER NOT NULL ENABLE, 
	"ID_RCT" NUMBER NOT NULL ENABLE, 
	"QTD_PROD" NUMBER NOT NULL ENABLE, 
	"COD_LOTE" NUMBER
   ) ;

  CREATE TABLE "RECEITA_AUXILIAR" 
   (	"ID_RCT" NUMBER, 
	"DS_RCT" VARCHAR2(120), 
	"CPF_CLIENTE" VARCHAR2(14), 
	"NM_MEDICO" VARCHAR2(120), 
	"ID_POSTO" NUMBER, 
	"DTA_PED" DATE
   ) ;

  CREATE TABLE "REGISTRO" 
   (	"USUARIO" VARCHAR2(50), 
	"DATA" DATE, 
	"DS_REG" VARCHAR2(120), 
	"TIPO" VARCHAR2(20)
   ) ;

  CREATE TABLE "STATUS" 
   (	"ID_STATUS" NUMBER, 
	"DS_STATUS" VARCHAR2(25), 
	 CONSTRAINT "PK_ID_STATUS" PRIMARY KEY ("ID_STATUS")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "TIPOS_PEDIDOS" 
   (	"ID_TIP_PED" NUMBER, 
	"DS_TIP_PED" VARCHAR2(50), 
	 CONSTRAINT "PK_ID_TIP_PED" PRIMARY KEY ("ID_TIP_PED")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "TIPO_POSTOS" 
   (	"ID_TIP_POSTO" NUMBER, 
	"DS_TIP_POSTO" VARCHAR2(50), 
	 CONSTRAINT "PK_ID_TIP_POSTO" PRIMARY KEY ("ID_TIP_POSTO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USUARIOS" 
   (	"ID" NUMBER, 
	"NOME" VARCHAR2(50), 
	"SOBRENOME" VARCHAR2(50), 
	"USUARIO" VARCHAR2(20), 
	"SENHA" VARCHAR2(25), 
	"STATUS" VARCHAR2(1), 
	"PERMISSAO" VARCHAR2(10), 
	"ID_FUNC" NUMBER, 
	"ID_FUNCAO" NUMBER, 
	 UNIQUE ("USUARIO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PK_ID_USUARIO" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USUARIOS_POSTOS" 
   (	"ID_USUARIO" NUMBER, 
	"ID_POSTO" NUMBER
   ) ;

  ALTER TABLE "FUNCIONARIOS" ADD CONSTRAINT "FK_ID_FUNCAO" FOREIGN KEY ("ID_FUNCAO")
	  REFERENCES "PROFISSOES" ("ID_FUNCAO") ENABLE;

  ALTER TABLE "PEDIDOS" ADD CONSTRAINT "FK_ID_FUNC" FOREIGN KEY ("ID_FUNC")
	  REFERENCES "FUNCIONARIOS" ("ID_FUNC") ENABLE;
  ALTER TABLE "PEDIDOS" ADD CONSTRAINT "FK_ID_POSTOS_PEDIDOS" FOREIGN KEY ("ID_POSTO")
	  REFERENCES "POSTOS" ("ID_POSTO") ENABLE;
  ALTER TABLE "PEDIDOS" ADD CONSTRAINT "FK_ID_STATUS_PEDIDOS" FOREIGN KEY ("ID_STATUS")
	  REFERENCES "STATUS" ("ID_STATUS") ENABLE;

  ALTER TABLE "PEDIDOS_PRODUTOS" ADD CONSTRAINT "FK_COD_PED" FOREIGN KEY ("COD_PED")
	  REFERENCES "PEDIDOS" ("COD_PED") ENABLE;
  ALTER TABLE "PEDIDOS_PRODUTOS" ADD CONSTRAINT "FK_COD_PROD" FOREIGN KEY ("COD_PROD")
	  REFERENCES "PRODUTOS" ("COD_PROD") ENABLE;

  ALTER TABLE "POSTOS" ADD CONSTRAINT "FK_TIP_POSTO_POSTOS" FOREIGN KEY ("ID_TIP_POSTO")
	  REFERENCES "TIPO_POSTOS" ("ID_TIP_POSTO") ENABLE;

  ALTER TABLE "POSTOS_PRODUTOS" ADD CONSTRAINT "FK_POSTOS_PRODUTOS_2" FOREIGN KEY ("COD_PROD")
	  REFERENCES "PRODUTOS" ("COD_PROD") ON DELETE SET NULL ENABLE;

  ALTER TABLE "PRODUTOS" ADD CONSTRAINT "FK_ID_COMP" FOREIGN KEY ("ID_COMP")
	  REFERENCES "COMPONENTES" ("ID_COMP") ENABLE;
  ALTER TABLE "PRODUTOS" ADD CONSTRAINT "FK_ID_DISP" FOREIGN KEY ("ID_DISP")
	  REFERENCES "DISPENSARIOS" ("ID_DISP") ENABLE;

  ALTER TABLE "RECEITAS" ADD CONSTRAINT "FK_ID_FUNC_RECEITAS" FOREIGN KEY ("ID_FUNC")
	  REFERENCES "FUNCIONARIOS" ("ID_FUNC") ENABLE;
  ALTER TABLE "RECEITAS" ADD CONSTRAINT "FK_ID_POSTO_RECEITAS" FOREIGN KEY ("ID_POSTO")
	  REFERENCES "POSTOS" ("ID_POSTO") ENABLE;

  ALTER TABLE "RECEITAS_PRODUTOS" ADD CONSTRAINT "FK_COD_PROD_REC" FOREIGN KEY ("COD_PROD")
	  REFERENCES "PRODUTOS" ("COD_PROD") ENABLE;
  ALTER TABLE "RECEITAS_PRODUTOS" ADD CONSTRAINT "FK_ID_RCT" FOREIGN KEY ("ID_RCT")
	  REFERENCES "RECEITAS" ("ID_RCT") ENABLE;

  ALTER TABLE "USUARIOS" ADD CONSTRAINT "FK_ID_FUNC_USUARIOS" FOREIGN KEY ("ID_FUNC")
	  REFERENCES "FUNCIONARIOS" ("ID_FUNC") ENABLE;

  ALTER TABLE "USUARIOS_POSTOS" ADD CONSTRAINT "FK_ID_POSTO" FOREIGN KEY ("ID_POSTO")
	  REFERENCES "POSTOS" ("ID_POSTO") ENABLE;
  ALTER TABLE "USUARIOS_POSTOS" ADD CONSTRAINT "FK_ID_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "USUARIOS" ("ID") ENABLE;